version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed."
  build:
    commands:
      - echo "Build started on `date`"
  post_build:
    commands:
      - echo "Deploying to S3..."
      # Sync files to your S3 bucket
      - aws s3 sync . s3://nathan-exp-9-devops --delete